### ISSUE TITLE
[docs] Wrong function name?

### ISSUE THREAD

**Issue by mauricioabreu** [hugoabonizio/timeout.cr#1]
In the documentation it says we should call `after` function but the code says `after_select_action`.
What is the right way to use the library?

PS.: I did not test it. I was just reading the code and wondered if it was right.

**Comment by hugoabonizio** [comment]
Hi @mauricioabreu! That's the patern of the new [select keyword](https://github.com/crystal-lang/crystal/pull/3130), see: https://github.com/crystal-lang/crystal/blob/13b11d7c65c48c03f985d4beb7e2a97805ebc7dc/src/compiler/crystal/semantic/literal_expander.cr#L527

**Comment by mauricioabreu** [comment]
Ooops! I was not aware of it. Thank you!

Good job!

**Comment by hugoabonizio** [comment]
@mauricioabreu In Crystal everyday we learn a new thing :smile:
